### ISSUE TITLE
GA not working in googleAnalyticsHook

### ISSUE THREAD

**Issue by kolkov** [ui-router/sample-app-angular#7]
Hi!
I try to debug GA with Google Analytics Debugger and I see than data not send to Google when page changes. ((
Data sends only if page is reload...
![image](https://user-images.githubusercontent.com/3740898/28842162-470f91a8-7705-11e7-91c2-c4f82b06aacf.png)

**Comment by kolkov** [comment]
This worked!

![image](https://user-images.githubusercontent.com/3740898/28842604-ea293c30-7706-11e7-9f11-d78168d95c3c.png)
![image](https://user-images.githubusercontent.com/3740898/28842643-1e57d9c6-7707-11e7-81b4-b2f32ee28646.png)

**Comment by christopherthielen** [comment]
Thanks for finding this.  I have no idea what is happening, but your code does indeed work!
